#!/usr/bin/env bash
# install nginx to create html pages - 404
apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html/;
        index index.html index.htm;

        error_page 404 /404.html;
        location /404 {
                root /var/www/html;
                internal;
              }
}
" > /etc/nginx/sites-available/default
sed -i "30i $REDIR" $SRC

service nginx restart                                                  1,1           Top
