#!/usr/bin/env bash
# install load balancer
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt show haproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo -e "\nlisten www" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind :80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver gc-12071-web-01 34.226.233.255" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver gc-12071-web-02 3.236.245.170" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
