#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive of it

curr=`date +"%d%m%Y"`
mysqldump -u root -p"$1" --all-databases --result-file=backup.sql
tar -czvf "$curr.tar.gz" backup.sql
